### ISSUE TITLE
2024-02-18 pseudo selector in css can "listen" for simple events

### ISSUE THREAD

**Issue by soraraso42** [soraraso42/learning-journal#22]
1. **:hover** - Selects an element when the user hovers over it.
   ```css
   button:hover {
       background-color: lightblue;
   }
   ```

2. **:active** - Selects an element when it is being activated (pressed down) by the user.
   ```css
   a:active {
       color: red;
   }
   ```

3. **:focus** - Selects an element when it has focus (e.g., clicked or tabbed into).
   ```css
   input:focus {
       border: 2px solid blue;
   }
   ```

4. **:nth-child(n)** - Selects the nth child of its parent.
   ```css
   li:nth-child(odd) {
       background-color: #f2f2f2;
   }
   ```

5. **:nth-of-type(n)** - Selects the nth child of its type.
   ```css
   p:nth-of-type(2n) {
       font-weight: bold;
   }
   ```

6. **:not(selector)** - Selects all elements that do not match the given selector.
   ```css
   input:not([type="text"]) {
       opacity: 0.5;
   }
   ```

7. **:first-child** - Selects the first child of its parent.
   ```css
   div > p:first-child {
       color: green;
   }
   ```

8. **:last-child** - Selects the last child of its parent.
   ```css
   ul > li:last-child {
       border-bottom: 1px solid #ccc;
   }
   ```
