### ISSUE TITLE
azure config for dotnet core app

### ISSUE THREAD

**Issue by soraraso42** [soraraso42/learning-journal#48]
Great choice! Going with **Azure SQL** will streamline your deployment and production processes, especially since you're deploying the app to Azure. Below is a **detailed, actionable to-do list** with specific tasks to get Azure SQL up and running and integrate it into your project efficiently. I've also included tasks related to connecting Azure SQL with your ASP.NET Core project and setting up CI/CD.

---

### **Detailed To-Do List for Azure SQL Setup and Integration**

---

#### **1. Set Up Azure SQL (Database-as-a-Service)**
1. **Sign Up and Access Azure Portal**
   - If you don’t already have an account, sign up at [Azure Portal](https://portal.azure.com/).
   - Access the portal and familiarize yourself with the dashboard.

2. **Create a Resource Group**
   - In Azure, resource groups logically group related resources like your app, database, and storage.
   - Navigate to **Resource Groups** and create a new one.
     - **Name**: Something relevant like `PortfolioApp-RG`.
     - **Region**: Choose the closest data center for optimal performance.
     - This will hold your Azure SQL Database and App Services.
  
3. **Provision an Azure SQL Database**
   - In the Azure portal, go to **Create a Resource** and search for **Azure SQL**.
   - Click **SQL Database** and select **Create**.
     - **Database name**: e.g., `PortfolioDB`.
     - **Resource Group**: Choose the one you created earlier (`PortfolioApp-RG`).
     - **Server**: You’ll need to create a SQL Server (if you don’t have one).
         - **Server name**: Something like `portfolio-sqlserver`.
         - **Location**: Same region as the resource group.
         - **Authentication**: Choose **SQL authentication**.
         - **Admin username**: e.g., `portfolioadmin`.
         - **Password**: Create a secure password for the admin.
     - **Compute + Storage**: Start with the **Basic** pricing tier or **Free Trial** if available.
     - **Backup storage redundancy**: You can leave this at the default option.
   
4. **Configure SQL Server Firewall (Allow Your IP)**
   - After creating the SQL Server, go to **Settings > Networking**.
   - In **Firewall rules**, add a new rule to allow your IP address (your local machine's IP) so you can access the database locally.
     - Rule name: `AllowLocalAccess`.
     - Start/End IP: Enter your current public IP address (check with `What is my IP` in a browser).
   - Save the firewall rule.

---

#### **2. Connect Azure SQL to Your ASP.NET Core Project**

1. **Install SQL Server Management Studio (SSMS) or Azure Data Studio** *(Optional but recommended for managing your DB easily)*:
   - Download [SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms).
   - You can use this tool to manage the database, run queries, and update tables.

2. **Create Database Schema in Azure SQL**:
   - Connect to your Azure SQL instance using **SSMS** or **Azure Data Studio** with the credentials you created (Admin username and password).
   - Create your **jokes** and **user profiles** tables:
     ```sql
     CREATE TABLE Jokes (
         Id INT PRIMARY KEY IDENTITY,
         Setup NVARCHAR(255),
         Punchline NVARCHAR(255),
         CreatedAt DATETIME DEFAULT GETDATE()
     );

     CREATE TABLE Users (
         Id INT PRIMARY KEY IDENTITY,
         Name NVARCHAR(100),
         Email NVARCHAR(100),
         PasswordHash NVARCHAR(255) -- If you plan to implement authentication
     );
     ```
   - This sets up your initial database structure.

3. **Configure Connection String in ASP.NET Core Project**:
   - In your **appsettings.json**, add the Azure SQL connection string:
     ```json
     {
       "ConnectionStrings": {
         "DefaultConnection": "Server=tcp:portfolio-sqlserver.database.windows.net,1433;Database=PortfolioDB;User ID=portfolioadmin;Password=YourPassword;Encrypt=true;Connection Timeout=30;"
       }
     }
     ```
   - Ensure to replace `YourPassword` with your actual admin password.

4. **Install Entity Framework Core (EF Core)**:
   - In your **ASP.NET Core** project, install Entity Framework Core and the SQL Server provider using NuGet Package Manager:
     ```bash
     dotnet add package Microsoft.EntityFrameworkCore.SqlServer
     dotnet add package Microsoft.EntityFrameworkCore.Tools
     ```
   - Update your **Startup.cs** or **Program.cs** to configure the database context:
     ```csharp
     public class Startup
     {
         public void ConfigureServices(IServiceCollection services)
         {
             services.AddDbContext<ApplicationDbContext>(options =>
                 options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
         }
     }
     ```

5. **Create and Apply Migrations**:
   - Generate a migration to create the database schema in Azure SQL from your EF Core models.
     ```bash
     dotnet ef migrations add InitialCreate
     dotnet ef database update
     ```
   - This will apply the schema changes (create tables) in your Azure SQL instance.

---

#### **3. Set Up CI/CD Pipeline with GitHub Actions for Azure**

1. **Set Up a GitHub Repository (if not done already)**:
   - Push your code to **GitHub** if you haven’t yet.
   - Make sure your `.gitignore` file includes sensitive files such as `appsettings.json` or use environment variables for secrets.

2. **Create GitHub Actions Workflow**:
   - In your GitHub repo, under **.github/workflows/**, create a new file (e.g., `azure.yml`) for your GitHub Actions pipeline:
     ```yaml
     name: Build and Deploy to Azure

     on:
       push:
         branches:
           - main

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up .NET Core
             uses: actions/setup-dotnet@v1
             with:
               dotnet-version: '6.0.x'

           - name: Build
             run: dotnet build --configuration Release

           - name: Run tests
             run: dotnet test --no-build --verbosity normal

       deploy:
         runs-on: ubuntu-latest
         needs: build
         steps:
           - name: Deploy to Azure Web App
             uses: azure/webapps-deploy@v2
             with:
               app-name: 'PortfolioApp' # Name of your Azure App Service
               slot-name: 'production'
               publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
     ```
   - You’ll need to create a **publish profile** from your Azure App Service and add it to your GitHub secrets (`AZURE_WEBAPP_PUBLISH_PROFILE`).

3. **Set Up Azure App Service to Automatically Pick Up Changes**:
   - Make sure your **App Service** in Azure is set to automatically deploy on commits to **GitHub** (set this up in **Deployment Center** in the Azure portal).

---

#### **4. Final Preparations**
1. **Test Local and Remote Connections**:
   - Locally run your app and ensure it can connect to **Azure SQL**.
   - Push your changes to GitHub and check that **GitHub Actions** builds and deploys your app to Azure.

2. **Monitoring and Logs**:
   - In the Azure portal, configure **Azure Monitor** to track application performance (errors, downtime, SQL performance).
   - Set up basic alerts for things like CPU usage or failed deployments.

---

### **Final Thoughts**
By following this plan, you’ll have Azure SQL integrated with your **ASP.NET Core** project, a working CI/CD pipeline, and a streamlined setup that allows for easy management and deployment. Focusing on this setup will significantly reduce complexity during the deployment phase, especially since Azure SQL is already part of the Azure ecosystem.
